### ISSUE TITLE
Unable to patch on LG Nexus 5X - Android 6.0.1

### ISSUE THREAD

**Issue by ghost** [moosd/Needle#16] opened 2016-06-02 10:40 UTC
Hello,
I have an error when patching my phone, the framework it pulls does not appear to contain the correct files.
- Phone:  I have an LG Nexus 5X and am using the latest stable version (20160505-0315.v10.2-OFFICIAL) of [Dirty Unicorns](http://forum.xda-developers.com/nexus-5x/orig-development/rom-dirty-unicorns-6-0-1-bullhead-03-01-t3326395), a ROM based on AOSP 6.0.1
- Computer: I am running Archlinux, with the latest android sdk installed from the official google  website. 

When running the script, I have the following output:

```
12:28 $ python3 patch.py 
 *** Selected device 0218fade53830a84
 *** Device detected! proceeding...
 *** Working dir: /tmp/tmpiw3k7r9z
 *** Rooting adbd...
adbd is already running as root
remount succeeded
 *** Pulling framework from device...
7 KB/s (309 bytes in 0.042s)
 *** Disassembling framework...
I: Using Apktool 2.0.2 on framework.jar
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
 *** Done. Now this won't hurt a bit...
Traceback (most recent call last):
  File "patch.py", line 47, in <module>
    f = open(to_patch, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'framework.jar.out/smali/android/content/pm/PackageParser.smali'
```

And the temporary directory structure is  the following:

```
12:37 $ tree /tmp/tmpiw3k7r9z/
/tmp/tmpiw3k7r9z/
├── framework.jar
└── framework.jar.out
    ├── apktool.yml
    └── original
        └── META-INF
            └── MANIFEST.MF

3 directories, 3 files
```

Please ask  if you need any further information.
Thank you.

**Comment by lmshk** [comment] 2016-06-04 10:48
I have exactly the same problem on:
- Arch Linux
- Nexus 5X
- **Cyanogen 13** (cm-13.0-20160418-SNAPSHOT-ZNH0EAO2NH-bullhead)

This ticket seems to be an exact duplicate of #4 and #14.

**Comment by fyrak1s** [comment] 2016-07-21 09:55
Got the same issue using:
- Windows 7 64 bit
- Moto G 2014 (Dual SIM)
- CM 13 (cm-13.0.20160710-NIGHLTY-titan)

Any solution/workaround for this??

**Comment by ghost** [comment] 2016-07-21 10:05
@moosd doesn't seem to be interested to fix this... 
It appears that the structure changed in Android, what would be needed would be to go see where the code now resides... I unfortunately really don't have time now, one of you guys up to it @Nuc1eoN @lmshk?

**Comment by fyrak1s** [comment] 2016-07-21 10:37
@Phenitei no, actually after reading #4 it seems that in newer Andorid/CM versions `framework.jar` is odexed and as such empty. The code resides in `/system/framework/arm/boat.oat` now. Starting with Marshmallow smali supports deodexing this file, so this should be fine for cm13.

I guess it should be easy to fix (for Marshmallow at least), but since I am not a coder I won't take up the task.

**Comment by ghost** [comment] 2016-07-21 10:42
@Nuc1eoN Noted. Maybe I'll have more time by the end of summer. I'll post something here if I find a solution.

**Comment by trogdor247** [comment] 2016-08-10 10:15
This amazing utility is still broken due to the above problem. Yet people are still recommending it and pointing people here. Any headway from @moosd or @Phenitei ? I would really like to run this through the CM13 20160418 snapshot for my new Nexus 5X.

**Comment by ale5000-git** [comment] 2016-08-14 02:39
@Nuc1eoN @Phenitei @trogdor247 I'm interested in fixing it if some of you can help.

If possible can someone create an issue in my fork ( https://github.com/ale5000-git/tingle ) and provide the original unpatched files: /system/framework/framework.jar and  /system/framework/arm/boat.oat please?

**Closed as completed** 2023-02-12 14:48 UTC
